services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production
    container_name: fruit-delivery
    restart: unless-stopped
